blueprint:
  name: Samsung AC Error Notification
  description: Sends a notification when an error code is detected on a Samsung AC unit.
  domain: automation
  input:
    error_code_sensor:
      name: Error Code Sensor
      description: Select the sensor that monitors error codes.
      selector:
        entity:
          domain: sensor
    notify_device:
      name: Notification Device
      description: Select the mobile app to receive the notifications.
      selector:
        entity:
          domain: mobile_app

trigger:
  - platform: state
    entity_id: !input error_code_sensor

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == '201' }}"
        sequence:
          - service: "notify.mobile_app_{{ state_attr(!input notify_device, 'id') }}"
            data:
              message: "Communication error between indoor and outdoor units."
              title: "Samsung AC Error"
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == '202' }}"
        sequence:
          - service: "notify.mobile_app_{{ state_attr(!input notify_device, 'id') }}"
            data:
              message: "Indoor unit sensor error (open circuit, short circuit, etc.)."
              title: "Samsung AC Error"
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == '203' }}"
        sequence:
          - service: "notify.mobile_app_{{ state_attr(!input notify_device, 'id') }}"
            data:
              message: "Fan motor error."
              title: "Samsung AC Error"
    default:
      - service: "notify.mobile_app_{{ state_attr(!input notify_device, 'id') }}"
        data:
          message: "Unknown error detected."
          title: "Samsung AC Error"
