blueprint:
  name: Samsung AC Error Notification
  description: Sends a notification when an error code is detected on a Samsung AC unit.
  domain: automation
  source_url: https://github.com/omerfaruk-aran/esphome_samsung_ac_blueprint
  input:
    error_code_sensor:
      name: Error Code Sensor
      description: Select the sensor that monitors error codes.
      selector:
        entity:
          domain: sensor
    notify_device:
      name: Notification Device
      description: Select the device to receive the notifications.
      selector:
        device:
          filter:
            integration: mobile_app

trigger:
  - platform: state
    entity_id: !input error_code_sensor

variables:
  error_code: "{{ trigger.to_state.state }}"
  notify_service: "notify.mobile_app_{{ device_attr(!input notify_device, 'name') | slugify }}"

sequence:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ error_code == '201' }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              title: "Samsung AC Error"
              message: "Communication error between indoor and outdoor units."
      - conditions:
          - condition: template
            value_template: "{{ error_code == '202' }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              title: "Samsung AC Error"
              message: "Indoor unit sensor error."
      - conditions:
          - condition: template
            value_template: "{{ error_code == '203' }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              title: "Samsung AC Error"
              message: "Fan motor error."
    default:
      - service: "{{ notify_service }}"
        data:
          title: "Samsung AC Error"
          message: "Unknown error detected."

mode: single
