blueprint:
  name: Samsung AC Error Notification
  description: Sends a notification when an error code is detected on a Samsung AC unit.
  domain: automation
  input:
    error_code_sensor:
      name: Error Code Sensor
      description: Select the sensor that monitors error codes.
      selector:
        entity:
          domain: sensor
    notification_device:
      name: Notification Device
      description: Select the device you want to receive notifications on.
      selector:
        device:
          integration: mobile_app

trigger:
  platform: state
  entity_id: !input error_code_sensor
  to: 
    - "201"
    # Add additional error codes here...

action:
  - service: >
      {% set notify_service = "notify.mobile_app_" + device_attr(notify_device, "name") | replace(" ", "_") %}
      {{ notify_service }}
    data:
      message: >
        {% if trigger.to_state.state == '201' %}
          Communication error between indoor and outdoor units (installation number setting error, repeated indoor unit address, indoor unit communication cable error).
        {% elif trigger.to_state.state == '202' %}
          Indoor unit sensor error (open circuit, short circuit, etc.).
        {% elif trigger.to_state.state == '203' %}
          Fan motor error.
        {% else %}
          Unknown error detected.
        {% endif %}
      title: "Samsung AC Error"
        # Add more conditions for other error codes

mode: single
