blueprint:
  name: Samsung AC Error Notification
  description: >
    This blueprint monitors a selected sensor for specific error codes from Samsung AC units and sends notifications to chosen devices. 
    The notifications will include a detailed error message corresponding to the detected error code.
  domain: automation
  source_url: https://github.com/omerfaruk-aran/esphome_samsung_ac_blueprint

input:
  sensor_entity:
    name: "Error Code Sensor"
    description: "Select the sensor that monitors the AC error codes."
    selector:
      entity:
        domain: sensor
  notify_device:
    name: "Device to notify"
    description: "Device that will receive the error notifications. Requires Home Assistant app."
    selector:
      device:
        integration: mobile_app

variables:
  error_code: "{{ states(sensor_entity) }}"
  error_message: >
    {% if error_code == '201' %}
      "Communication error between indoor and outdoor units."
    {% else %}
      "Unknown error. Please refer to the AC unit's manual."
    {% endif %}

trigger:
  - platform: state
    entity_id: !input sensor_entity

condition:
  - condition: template
    value_template: "{{ error_code in ['201'] }}"

action:
  - service: notify.mobile_app_omer15promax
    data:
      target: "{{ device_attr(notify_device, 'name') | replace(' ', '_') }}"
      title: "Samsung AC Error Detected"
      message: "{{ error_message }}"

mode: single
