blueprint:
  name: Samsung AC Error Notification
  description: Sends a notification when an error code is detected on a Samsung AC unit.
  domain: automation
  source_url: https://github.com/omerfaruk-aran/esphome_samsung_ac_blueprint
  input:
    error_code_sensor:
      name: Error Code Sensor
      description: Select the sensor that monitors error codes.
      selector:
        entity:
          domain: sensor
    notify_device:
      name: Notification Device
      description: Select the device to receive the notifications.
      selector:
        device:
          filter:
            integration: mobile_app
    title:
      name: Notification Title
      description: Title of the notification.
      default: "Samsung AC Error"
      selector:
        text:
    message_201:
      name: Error 201 Message
      description: Message for error code 201.
      default: "Communication error between indoor and outdoor units."
      selector:
        text:
    message_202:
      name: Error 202 Message
      description: Message for error code 202.
      default: "Indoor unit sensor error."
      selector:
        text:
    message_203:
      name: Error 203 Message
      description: Message for error code 203.
      default: "Fan motor error."
      selector:
        text:
    default_message:
      name: Default Error Message
      description: Message for unknown error codes.
      default: "Unknown error detected."
      selector:
        text:

trigger:
  - platform: state
    entity_id: !input error_code_sensor

variables:
  error_code: "{{ trigger.to_state.state }}"

sequence:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ error_code == '201' }}"
        sequence:
          - service: "notify.mobile_app_{{ device_attr(!input notify_device, 'name') | slugify }}"
            data:
              title: !input title
              message: !input message_201
      - conditions:
          - condition: template
            value_template: "{{ error_code == '202' }}"
        sequence:
          - service: "notify.mobile_app_{{ device_attr(!input notify_device, 'name') | slugify }}"
            data:
              title: !input title
              message: !input message_202
      - conditions:
          - condition: template
            value_template: "{{ error_code == '203' }}"
        sequence:
          - service: "notify.mobile_app_{{ device_attr(!input notify_device, 'name') | slugify }}"
            data:
              title: !input title
              message: !input message_203
    default:
      - service: "notify.mobile_app_{{ device_attr(!input notify_device, 'name') | slugify }}"
        data:
          title: !input title
          message: !input default_message

mode: single
