blueprint:
  name: Samsung AC Error Notification
  description: Sends a notification when an error code is detected on a Samsung AC unit.
  domain: automation
  input:
    error_code_sensor:
      name: Error Code Sensor
      description: Select the sensor that monitors error codes.
      selector:
        entity:
          domain: sensor
    notification_device:
      name: Notification Device
      description: Select the device you want to receive notifications on.
      selector:
        device:
          integration: mobile_app

trigger:
  platform: state
  entity_id: !input error_code_sensor

action:
  - variables:
      notify_service: >
        notify.mobile_app_{{ device_attr(!input notify_device, "name") | replace(" ", "_") }}
      error_code: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ error_code == '201' }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              message: "Communication error between indoor and outdoor units."
              title: "Samsung AC Error"

mode: single
